from marshmallow import fields
from . import ma

class EventSchema(ma.Schema):
    id = fields.Integer(required=False) # id is autogenerated
    event_name = fields.String(required=True)
    description = fields.String(required=True)
    event_date = fields.String(required=True)
    venue = fields.String(required=True)
    start_time = fields.String(required=True)
    end_time = fields.String(required=True)
    event_type = fields.String(required=True)
    music_type = fields.String(required=True)
    organizer = fields.String(required=True)
    entry_fees = fields.String(required=True)
    
    class Meta:
        fields = ("id", "event_name", "description", "event_date", "venue", "start_time", "end_time", "event_type", "music_type", "organizer", "entry_fees")

event_schema = EventSchema()


